name: update_plots

on:
  schedule:
   - cron: "0 8 * * *"
jobs:
  update_plots:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
        
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install packages
        run: |
          install.packages("RcppRoll", dependencies = TRUE)
          install.packages("dplyr", dependencies = TRUE)
          install.packages("lubridate", dependencies = TRUE)
          install.packages("readr", dependencies = TRUE)
          install.packages("ggplot2", dependencies = TRUE)
          install.packages("data.table", dependencies = TRUE)
          install.packages("remotes", dependencies = TRUE)
        shell: Rscript {0}
      
      - name: Check capabilities
        run: |
          capabilities()
        shell: Rscript {0}
        
      - name: Run script
        run: | 
          source("impfquote_hospitalisierung.R")
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add --all
          git commit -am "add data"
          git push 
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: gitub-actions
