name: update_plots

on:
  schedule:
    - cron: "0 10 * * *"
jobs:
  update_plots:
    runs-on: macos-latest
    steps:
      - name: Setup
        uses: actions/checkout@master
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
        
      - name: Install packages
        run: |
          R -e 'install.packages("RcppRoll", dependencies = TRUE)'
          R -e 'install.packages("tidyverse", dependencies = TRUE)'
          R -e 'install.packages("data.table", dependencies = TRUE)'
          R -e 'install.packages("remotes", dependencies = TRUE)'
          
      - name: Run script
        run: | 
          RScript impfquote_hospitatlisierung.R
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: gitub-actions